development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: thuy
  pool: 5
  username: netmile
  password: netmile123
  host: dev-vpc.cb5wgkbfnfgu.ap-northeast-1.rds.amazonaws.com
  port: 3306